const state = { stocks: [], market: {}, filtered: [] };
const $ = (selector) => document.querySelector(selector);

function isPositive(value) { return Number.isFinite(Number(value)) && Number(value) > 0; }
function securityId(stock) { return `${stock.code}.${stock.exchange}`; }
function number(value, digits = 2) { return isPositive(value) ? Number(value).toFixed(digits) : "–"; }
function price(value) { return isPositive(value) ? `¥${number(value)}` : "行情缺失"; }
function yieldPercent(dividend, currentPrice) { return isPositive(dividend) && isPositive(currentPrice) ? Number(dividend) / Number(currentPrice) * 100 : null; }
function priceAtYield(dividend, targetYield) { return isPositive(dividend) && isPositive(targetYield) ? Number(dividend) / (Number(targetYield) / 100) : null; }
function gridValues(minimum, maximum, step) { const out = []; if (!isPositive(minimum) || !isPositive(maximum) || !isPositive(step)) return out; for (let n = Math.round(minimum * 10), max = Math.round(maximum * 10), delta = Math.round(step * 10); n <= max; n += delta) out.push(n / 10); return out; }

function zone(stock, currentPrice) {
  const low = Number(stock.target_low), high = Number(stock.target_high), target = Number(stock.target_price);
  if (isPositive(low) && isPositive(high) && isPositive(currentPrice)) {
    if (currentPrice < low) return { key: "deep", label: "🔥 深入击球区", detail: `低于下沿 ${number((low - currentPrice) / low * 100, 1)}%` };
    if (currentPrice <= high) return { key: "in", label: "🟢 已进入击球区", detail: `击球区 ¥${number(low)}–${number(high)}` };
    const distance = (currentPrice - high) / high * 100;
    if (distance <= 5) return { key: "near", label: "🟡 接近击球区", detail: `距离击球区 ${number(distance, 1)}%` };
    return { key: "wait", label: "⚪ 等待", detail: `距离击球区 ${number(distance, 1)}%` };
  }
  if (isPositive(target)) return { key: "wait", label: "⚪ 参考目标价", detail: `参考 ¥${number(target)}` };
  return { key: "wait", label: "⚪ 未设击球区", detail: "待维护" };
}

function quoteFor(stock) { return state.market.stocks?.[securityId(stock)] || null; }
function stockView(stock) { const quote = quoteFor(stock); const currentPrice = quote?.price; return { stock, quote, currentPrice, currentYield: yieldPercent(stock.annual_dividend, currentPrice), zone: zone(stock, currentPrice) }; }

function populateCategories() { const select = $("#category-filter"); [...new Set(state.stocks.map((s) => s.category))].sort().forEach((category) => { const option = document.createElement("option"); option.value = category; option.textContent = category; select.append(option); }); }
function renderMarketMeta() {
  const market = state.market; const date = market.updated_at ? new Date(market.updated_at).toLocaleString("zh-CN", { hour12: false }) : "尚未成功更新";
  $("#market-meta").textContent = `最近成功行情更新：${date}${market.source ? `　数据源：${market.source}` : ""}`;
  const box = $("#market-status"); box.textContent = market.message || "行情状态未知"; box.className = `data-status ${market.status === "normal" ? "" : market.status === "partial" ? "warn" : "error"}`;
  if (market.as_of) {
    const age = Math.floor((Date.now() - new Date(`${market.as_of}T00:00:00+08:00`).getTime()) / 86400000);
    if (age > 3 && market.status === "normal") { box.textContent = `最近行情日期为 ${market.as_of}，数据可能已过期。`; box.className = "data-status warn"; }
  }
}
function renderSummary(views) { const actionable = views.filter((view) => view.currentYield !== null); $("#total-count").textContent = state.stocks.length; $("#in-zone-count").textContent = views.filter((view) => view.zone.key === "in" || view.zone.key === "deep").length; $("#near-zone-count").textContent = views.filter((view) => view.zone.key === "near").length; $("#average-yield").textContent = actionable.length ? `${number(actionable.reduce((sum, view) => sum + view.currentYield, 0) / actionable.length)}%` : "–"; }
function card(view) { const { stock, quote, currentPrice, currentYield, zone: status } = view; const dividend = isPositive(stock.annual_dividend) ? `¥${number(stock.annual_dividend)}` : "分红待维护"; const target = isPositive(stock.target_low) && isPositive(stock.target_high) ? `¥${number(stock.target_low)}–${number(stock.target_high)}` : isPositive(stock.target_price) ? `参考 ¥${number(stock.target_price)}` : "未设置"; return `<button class="stock-card ${status.key}" data-id="${securityId(stock)}"><span class="stock-name"><strong>${stock.name}</strong><small>${stock.code}.${stock.exchange} · ${stock.category}</small></span><span class="metric"><small>现价</small><b>${price(currentPrice)}</b></span><span class="metric"><small>年度分红</small><b>${dividend}</b></span><span class="metric"><small>当前股息率</small><b>${currentYield === null ? "分红/行情待维护" : `${number(currentYield)}%`}</b></span><span class="metric"><small>击球区</small><b>${target}</b></span><span class="status ${status.key}">${status.label}<span class="submetric">${status.detail}</span></span></button>`; }
function sortViews(views) { const choice = $("#sort").value; const priority = { deep: 0, in: 1, near: 2, wait: 3 }; return views.sort((a, b) => { if (choice === "yield-desc") return (b.currentYield ?? -Infinity) - (a.currentYield ?? -Infinity); if (choice === "name") return a.stock.name.localeCompare(b.stock.name, "zh-CN"); if (choice === "distance") { const distance = (view) => isPositive(view.stock.target_high) && isPositive(view.currentPrice) ? Math.max(0, (view.currentPrice - view.stock.target_high) / view.stock.target_high) : Infinity; return distance(a) - distance(b); } return priority[a.zone.key] - priority[b.zone.key] || (b.currentYield ?? 0) - (a.currentYield ?? 0); }); }
function renderList() { const query = $("#search").value.trim().toLowerCase(); const category = $("#category-filter").value; let views = state.stocks.map(stockView).filter((view) => !category || view.stock.category === category).filter((view) => !query || [view.stock.name, view.stock.code, view.stock.category].join(" ").toLowerCase().includes(query)); views = sortViews(views); state.filtered = views; renderSummary(state.stocks.map(stockView)); $("#stock-list").innerHTML = views.length ? views.map(card).join("") : '<div class="empty">没有符合条件的股票。</div>'; document.querySelectorAll(".stock-card").forEach((button) => button.addEventListener("click", () => openDetail(button.dataset.id))); }
function openDetail(id) { const view = state.stocks.map(stockView).find((item) => securityId(item.stock) === id); if (!view) return; const { stock, quote, currentPrice, currentYield, zone: status } = view; const grids = gridValues(stock.grid_min, stock.grid_max, stock.grid_step); const closest = currentYield === null || !grids.length ? null : grids.reduce((best, value) => Math.abs(value - currentYield) < Math.abs(best - currentYield) ? value : best, grids[0]); const table = isPositive(stock.annual_dividend) ? `<table class="grid-table"><caption>${number(stock.grid_step, 1)}% 股息率价格网格</caption><thead><tr><th>股息率</th><th>对应股价</th><th>标记</th></tr></thead><tbody>${grids.map((value) => { const p = priceAtYield(stock.annual_dividend, value); const current = value === closest; const covered = isPositive(stock.target_low) && isPositive(stock.target_high) && p >= stock.target_low && p <= stock.target_high; return `<tr class="${current ? "current" : ""} ${covered ? "target" : ""}"><td>${number(value, 1)}%</td><td>¥${number(p)}</td><td>${current ? "现价附近" : covered ? '<span class="badge">击球区</span>' : ""}</td></tr>`; }).join("")}</tbody></table>` : '<p class="empty">分红待维护，暂无法生成股息率价格网格。</p>'; $("#detail-content").innerHTML = `<div class="detail-head"><h2 id="detail-title">${stock.name}</h2><p class="security-code">${securityId(stock)} · ${stock.category}</p></div><p class="status ${status.key}">${status.label}　${status.detail}</p><div class="detail-metrics"><div><span>现价</span><b>${price(currentPrice)}</b></div><div><span>年度分红</span><b>${isPositive(stock.annual_dividend) ? `¥${number(stock.annual_dividend)}` : "分红待维护"}</b></div><div><span>当前股息率</span><b>${currentYield === null ? "–" : `${number(currentYield)}%`}</b></div><div><span>击球区</span><b>${isPositive(stock.target_low) ? `¥${number(stock.target_low)}–${number(stock.target_high)}` : "未设置"}</b></div><div><span>参考目标价</span><b>${isPositive(stock.target_price) ? `¥${number(stock.target_price)}` : "–"}</b></div><div><span>行情日期</span><b>${quote?.as_of || "行情缺失"}</b></div></div><p class="detail-note">${stock.dividend_note || ""}${stock.notes ? `　${stock.notes}` : ""}</p>${table}`; $("#detail-modal").showModal(); }
async function boot() { try { const request = { cache: "no-store" }; const [stocksResponse, marketResponse] = await Promise.all([fetch("./data/stocks.json", request), fetch("./data/market.json", request)]); if (!stocksResponse.ok) throw new Error("无法读取 stocks.json"); state.stocks = await stocksResponse.json(); state.market = marketResponse.ok ? await marketResponse.json() : { status: "unavailable", message: "无法读取 market.json", stocks: {} }; populateCategories(); renderMarketMeta(); renderList(); } catch (error) { $("#stock-list").innerHTML = `<div class="empty">页面数据读取失败：${error.message}</div>`; } }
["#search", "#category-filter", "#sort"].forEach((selector) => $(selector).addEventListener("input", renderList)); $("#close-modal").addEventListener("click", () => $("#detail-modal").close()); $("#detail-modal").addEventListener("click", (event) => { if (event.target === $("#detail-modal")) $("#detail-modal").close(); }); boot();
